package domain.usecase

import domain.model.BackupService
import domain.model.ImportResult
import domain.model.Transaction
import domain.model.TransactionType
import domain.repository.BackupRepository
import domain.repository.TransactionRepository

/**
 * Use case for importing data from a Google Spreadsheet backup.
 * This follows Clean Architecture principles - business logic in the domain layer.
 */
class ImportDataFromSpreadsheetUseCase(
    private val backupRepository: BackupRepository,
    private val transactionRepository: TransactionRepository,
) {
    /**
     * Imports data from a spreadsheet, replacing all existing data.
     * @param spreadsheetId The ID of the spreadsheet to import from
     * @param replaceExisting If true, deletes all existing transactions before importing
     * @return ImportResult indicating success or failure
     */
    suspend fun execute(spreadsheetId: String, replaceExisting: Boolean = true): ImportResult {
        val service = BackupService.GoogleDrive

        return try {
            if (!backupRepository.isAuthenticated(service)) {
                return ImportResult.SignInRequired
            }

            // Read data from spreadsheet
            val spreadsheetData = backupRepository.readSpreadsheetData(service, spreadsheetId)
                ?: return ImportResult.Error("Falha ao ler dados da planilha")

            if (spreadsheetData.rows.isEmpty()) {
                return ImportResult.Success(0)
            }

            // Parse transactions from spreadsheet data
            val transactions = parseTransactions(spreadsheetData.rows)

            if (transactions.isEmpty()) {
                return ImportResult.Success(0)
            }

            // Delete existing data if requested
            if (replaceExisting) {
                transactionRepository.deleteAllTransactions()
            }

            // Insert new transactions
            val insertedIds = transactionRepository.insertTransactions(transactions)

            ImportResult.Success(insertedIds.size)
        } catch (e: Exception) {
            ImportResult.Error("Falha ao importar dados da planilha", e)
        }
    }

    private fun parseTransactions(rows: List<List<String>>): List<Transaction> {
        return rows.mapNotNull { row ->
            try {
                // Expected format:
                // 0: ID, 1: Valor (centavos), 2: Tipo, 3: Categoria, 4: Descrição, 5: Data, 6: Recorrente, 7: Criado em
                if (row.size < 8) return@mapNotNull null

                val amountCents = row[1].toLongOrNull() ?: return@mapNotNull null
                val type = when (row[2]) {
                    "Receita" -> TransactionType.INCOME
                    "Despesa" -> TransactionType.EXPENSE
                    else -> return@mapNotNull null
                }
                val category = row[3].takeIf { it.isNotBlank() }
                val description = row[4].takeIf { it.isNotBlank() }
                val humanDate = row[5]
                val isRecurring = row[6] == "Sim"
                val createdAt = row[7].toLongOrNull() ?: 0L

                Transaction(
                    id = 0, // Will be auto-generated by database
                    amountCents = amountCents,
                    type = type,
                    category = category,
                    description = description,
                    humanDate = humanDate,
                    isRecurring = isRecurring,
                    createdAt = createdAt,
                )
            } catch (e: Exception) {
                null
            }
        }
    }
}
